# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - run: npm run build --if-present
      - name: Upload Pages artifact
        id: deploy
        uses: actions/upload-pages-artifact@v2
      - name: Make the script files executable
        run: chmod +x ./.github/scripts/telegram.sh
      - name: Conclusion
        id: conclusion
        run: ./.github/scripts/telegram.sh
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
          GITHUB_REF_NAME: ${{ secrets.GITHUB_REF_NAME }}
          GITHUB_SERVER_URL: ${{ secrets.GITHUB_SERVER_URL }}
          GITHUB_RUN_ID: ${{ secrets.GITHUB_RUN_ID }}
          STATUS: ${{ job.status }}
